### ISSUE TITLE
Default pet not as specified in config.

### ISSUE THREAD

**Issue by BrainStone** [Shynixn/PetBlocks#149]
The default pet I specified in the config does not work!

New players simply get a grass pet with no particle effects. Also it is not spawned by default (as it should according to my config)

Config:

```
join:
  enabled: true
  overwrite-previous-pet: false
  settings:
    petname: ":player's Tierchen"
    engine: 1
    id: 57
    damage: 0
    unbreakable: false
    skin: ''
    enabled: true
    age: 1
    effect:
      name: 'reddust'
      speed: 0.01
      amount: 20
      red: 0
      green: 0
      blue: 255
```

Versions:

- PetBlocks: 7.1.0-SNAPSHOT (btw it still says 7.0.1 ingame. Use `/sponge plugins petblocks` to see)
- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-7d8a938
- SpongeForge: 1.12.2-2655-7.1.0-BETA-3065
- Minecraft Forge: 14.23.3.2655
