### ISSUE TITLE
Engine with Entity:Zombie can't spawn in WorldGuard Region

### ISSUE THREAD

**Issue by ValerianV** [Shynixn/PetBlocks#181]
Hello,

To disable Zombie spawn in my WorldGuard region, i have set  the flag deny-mob: Zombie.

When i try to spawn an engine with the entity type 'ZOMBIE' in the region, i can't cause of the previous flag.

Here is my engine configuration: 
```yaml
 1:
     gui:
        id: 397
        damage: 3
        skin: 'textures.minecraft.net/texture/5657cd5c2989ff97570fec4ddcdc6926a68a3393250c1be1f0b114a1db1'
        name: '&e&lCat'
        unbreakable: false
        lore:
          - '&7Permission: <permission>'
     behaviour:
        entity: 'ZOMBIE'
        riding: 'RUNNING'
     sound:
        ambient:
           name: 'CAT_MEOW'
           volume: 1.0
           pitch: 1.0
        walking:
           name: 'WOLF_WALK'
           volume: 0.5
           pitch: 1.0
```
And now my startup logs : 

``
[18:34:56] [Server thread/INFO]: [PetBlocks] found dependency [WorldGuard].[m
[18:34:56] [Server thread/INFO]: [PetBlocks] hooked successfully into [WorldGuard] 6.2.2-SNAPSHOT;1710-95b88ea.[m
[18:34:56] [Server thread/INFO]: [PetBlocks] Enabled PetBlocks 7.2.0 by Shynixn[m
``

Thanks
