### ISSUE TITLE
Enhancement Suggestion: Ride speed modifier per engine

### ISSUE THREAD

**Issue by ValerianV** [Shynixn/PetBlocks#182]
It would be nice if we could set a speed modifier for each engine instead of for all engines.
Something like this : 
```yaml
engines:
   1:
     gui:
        id: 397
        damage: 3
        skin: 'textures.minecraft.net/texture/5657cd5c2989ff97570fec4ddcdc6926a68a3393250c1be1f0b114a1db1'
        name: '&e&lCat'
        unbreakable: false
        lore:
          - '&7Permission: <permission>'
     behaviour:
        entity: 'ZOMBIE'
        riding: 'RUNNING'
     sound:
        ambient:
           name: 'CAT_MEOW'
           volume: 1.0
           pitch: 1.0
        walking:
           name: 'WOLF_WALK'
           volume: 0.5
           pitch: 1.0
    modifier:    ####################### Here #######################
        riding-speed: 0.5
        walking-speed: 1.0
        climbing-height: 1.0
```
